response = {}

if @document.multires_image_file_paths.present?
  sources = image_item_tilesources(@document.multires_image_file_paths)
  response['tilesources'] = sources
end

# For now, only render derivative paths in media.json when they're external to DDR and 
# configured as such in a portal config. Revisit if in future we need to add to this stream:
# 1) media derivatives stored in / served by DDR
# 2) media derivatives generated by DDR (w/location recorded in item data)

if @derivative_url_prefixes.present?
  paths = derivative_urls({document: @document, derivative_url_prefixes: @derivative_url_prefixes})
  derivatives = paths.group_by{|path| File.extname(path)[1..-1]}
  response['derivatives'] = derivatives
end

response.to_json
